/**
 * food apiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { number, string } from '../schema';
import { BaseController } from './baseController';

export class MessageController extends BaseController {
  /**
   * recive message
   *
   * @return Response from the API call
   */
  async recivemessage(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/message/recive');
    return req.call(requestOptions);
  }

  /**
   * send message
   *
   * @param message
   * @param for     user id you want to send message
   * @return Response from the API call
   */
  async sendmessage(
    message: string,
    for: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/message/send');
    const mapped = req.prepareArgs({
      message: [message, string()],
      for: [for, number()],
    });
    req.form({
      message: mapped.message,
      for: mapped.for,
    });
    return req.call(requestOptions);
  }
}
