/**
 * food apiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { ApiError } from '@apimatic/core';
import { ApiResponse, RequestOptions } from '../core';
import { ReviewRequests, reviewRequestsSchema } from '../models/reviewRequests';
import { BaseController } from './baseController';

export class ReviewController extends BaseController {
  /**
   * post reviews for an order for each product in order
   *
   * @param reviewsObject
   * @return Response from the API call
   */
  async postreviws(
    reviewsObject: ReviewRequests,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<string>> {
    const req = this.createRequest('POST', '/review/add');
    const mapped = req.prepareArgs({
      reviewsObject: [reviewsObject, reviewRequestsSchema],
    });
    req.json(mapped.reviewsObject);
    req.throwOn(400, ApiError, 'bad request');
    return req.callAsText(requestOptions);
  }
}
