/**
 * food apiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { boolean, number, object, Schema } from '../schema';

export interface ActivateSwitchRequest {
  productId: number;
  switch: boolean;
}

export const activateSwitchRequestSchema: Schema<ActivateSwitchRequest> = object(
  { productId: ['product_id', number()], switch: ['switch', boolean()] }
);
