/**
 * food apiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Loginrequest {
  username: string;
  password: string;
}

export const loginrequestSchema: Schema<Loginrequest> = object({
  username: ['username', string()],
  password: ['password', string()],
});
