/**
 * food apiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface OrderDetails1 {
  orderDetailId: number;
  orderId: number;
  productCategoryId: string;
  productCategoryItemId: string;
  custom: string;
  itemPrice: number;
  itemQuantity: number;
  createdBy: number;
  mDelete: string;
  createdAt: string;
  updatedAt: string;
}

export const orderDetails1Schema: Schema<OrderDetails1> = object({
  orderDetailId: ['order_detail_id', number()],
  orderId: ['order_id', number()],
  productCategoryId: ['product_category_id', string()],
  productCategoryItemId: ['product_category_item_id', string()],
  custom: ['custom', string()],
  itemPrice: ['item_price', number()],
  itemQuantity: ['item_quantity', number()],
  createdBy: ['created_by', number()],
  mDelete: ['m_delete', string()],
  createdAt: ['created_at', string()],
  updatedAt: ['updated_at', string()],
});
