/**
 * food apiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface Order {
  orderId: number;
  orderUid: string;
  buyerId: number;
  totalProducts: number;
  totalAmount: number;
  active: number;
  canceled: number;
  completed: number;
  createdBy: number;
  deletedAt: string;
  mDelete: string;
  createdAt: string;
  updatedAt: string;
}

export const orderSchema: Schema<Order> = object({
  orderId: ['order_id', number()],
  orderUid: ['order_uid', string()],
  buyerId: ['buyer_id', number()],
  totalProducts: ['total_products', number()],
  totalAmount: ['total_amount', number()],
  active: ['active', number()],
  canceled: ['canceled', number()],
  completed: ['completed', number()],
  createdBy: ['created_by', number()],
  deletedAt: ['deleted_at', string()],
  mDelete: ['m_delete', string()],
  createdAt: ['created_at', string()],
  updatedAt: ['updated_at', string()],
});
