/**
 * food apiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface OrderItem {
  id: number;
  orderId: number;
  productId: number;
  amount: number;
  addedBy: number;
  createdAt: string;
  updatedAt: string;
}

export const orderItemSchema: Schema<OrderItem> = object({
  id: ['id', number()],
  orderId: ['order_id', number()],
  productId: ['product_id', number()],
  amount: ['amount', number()],
  addedBy: ['added_by', number()],
  createdAt: ['created_at', string()],
  updatedAt: ['updated_at', string()],
});
