/**
 * food apiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { array, boolean, lazy, object, Schema } from '../schema';
import { Order, orderSchema } from './order';
import { OrderDetails1, orderDetails1Schema } from './orderDetails1';
import { OrderItem, orderItemSchema } from './orderItem';

export interface OrderDetails {
  seccuss: boolean;
  order: Order[];
  orderDetails: OrderDetails1[];
  orderItems: OrderItem[];
}

export const orderDetailsSchema: Schema<OrderDetails> = object({
  seccuss: ['seccuss', boolean()],
  order: ['Order', array(lazy(() => orderSchema))],
  orderDetails: ['Order Details', array(lazy(() => orderDetails1Schema))],
  orderItems: ['Order Items', array(lazy(() => orderItemSchema))],
});
