/**
 * food apiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface ProductUpdateRequest {
  name: string;
  productId: string;
  discription: string;
  price: string;
  catagory: string;
}

export const productUpdateRequestSchema: Schema<ProductUpdateRequest> = object({
  name: ['name', string()],
  productId: ['product_id', string()],
  discription: ['discription', string()],
  price: ['price', string()],
  catagory: ['catagory', string()],
});
