/**
 * food apiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Product {
  productId: string;
  amount: string;
  custom: string;
}

export const productSchema: Schema<Product> = object({
  productId: ['product_id', string()],
  amount: ['amount', string()],
  custom: ['custom', string()],
});
