/**
 * food apiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Resetpasswordrequest {
  token: string;
  email: string;
  password: string;
}

export const resetpasswordrequestSchema: Schema<Resetpasswordrequest> = object({
  token: ['token', string()],
  email: ['email', string()],
  password: ['password', string()],
});
