/**
 * food apiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface Reviews1 {
  review: number;
  comment: string;
  productId: number;
}

export const reviews1Schema: Schema<Reviews1> = object({
  review: ['review', number()],
  comment: ['comment', string()],
  productId: ['product_id', number()],
});
