/**
 * food apiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Updateprofilerequest {
  name: string;
  description: string;
  typeOfBusiness: string;
  phone: string;
  email: string;
  halal: string;
}

export const updateprofilerequestSchema: Schema<Updateprofilerequest> = object({
  name: ['name', string()],
  description: ['Description', string()],
  typeOfBusiness: ['Type_of_Business', string()],
  phone: ['Phone', string()],
  email: ['email', string()],
  halal: ['halal', string()],
});
