/**
 * food apiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

import { Configuration, Environment } from './configuration';

/** Default values for the configuration parameters of the client. */
export const DEFAULT_CONFIGURATION: Configuration = {
  timeout: 0,
  authorization: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjE6NTAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTYxNjg1MDE4OCwiZXhwIjoxNjE2OTM2NTg4LCJuYmYiOjE2MTY4NTAxODgsImp0aSI6IlVHZ0h3SUFvaTNVSWlTMmoiLCJzdWIiOjUzLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.0R75IpG92siFIUM3AEMgzlwGm79vM--YuERu2T-f6Cs',
  environment: Environment.Production,
  accessToken: 'TODO access token',
};
